# -*- coding: utf-8 -*-
"""Combined Motion Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CxH9sxdj_HiyervLzgt7WmzZZN0No1GJ
"""

#**Combined Motion Analysis**
#Create a program that:

#Asks the user for initial velocity, acceleration, and time
#Calculates and displays: Final velocity, Displacement, Average velocity (hint: average velocity = displacement/time)
#Includes error handling for invalid inputs

def analyze_motion():
    """
    Get user input and display comprehensive motion analysis

    Returns:
    dict: Dictionary containing all calculated values
    None: If inputs are invalid
    """
    try:
        # Your code here for input and calculations
        pass
    except ValueError:
        print("Please enter valid numbers")
        return None

##My Code Here##
def analyze_motion():
    try:
      initial_velocity = float(input("Enter the initial velocity (m/s): "))
      acceleration = float(input("Enter the acceleration (m/s²): "))
      time = float(input("Enter the time (s): "))
      final_velocity = initial_velocity + (acceleration * time)
      rounded_number1=round(final_velocity,2)
      displacement = (initial_velocity * time) + (0.5 * acceleration * time**2)
      rounded_number2=round(displacement,2)
      average_velocity = displacement / time
      rounded_number3=round(average_velocity,2)
      results = {
            'Final Velocity (m/s)': rounded_number1,
            'Displacement (m)': rounded_number2,
            'Average Velocity (m/s)': rounded_number3,
            }
      return results
    except ValueError:
        print("Please enter valid numbers")
        return None
analyze_motion()


#SmapleInput1
#Enter the initial velocity (m/s): 0
#Enter the acceleration (m/s²): 9.81
#Enter the time (s): 2
#SampleOutput1
#{'Final Velocity (m/s)': 19.62,
 #'Displacement (m)': 19.62,
 #'Average Velocity (m/s)': 9.81}

#SampleInput2
#Enter the initial velocity (m/s): five
#SampleOutput2
#Please enter valid numbers
